split: ['train', 'dev']  # either 'train' or other 
data: 
  file_dir: ['./train_audios', './dev_audios']
  file_path: ['./train-answer-span.csv', './dev-answer-span.csv']
  hash2question_path: ['./train-hash2question.json', './dev-hash2question.json']
  ext: 'mp3'
  feature_selection: 12

hparas: 
  n_epoch: 3
  batch_size: 4
  optimizer: 'AdamW'
  lr: 5e-5

model: 
  hidden_size: 768
  num_attention_heads: 4
  nlayers: 3
  hidden_dropout_prob: 0.1
  intermediate_size: 2048
  hidden_act: 'gelu'
  layer_norm_eps: 1e-12
  num_labels: 2