split: ['train', 'dev']  # either 'train' or other 
data: 
  file_dir: ['/home/daniel094144/Daniel/SpokenQA/train_audios', '/home/daniel094144/Daniel/SpokenQA/dev_audios']
  file_path: ['/home/daniel094144/Daniel/SpokenQA/train_ans_reduced.csv', '/home/daniel094144/Daniel/SpokenQA/dev_ans_reduced.csv']
  hash2question_path: ['/home/daniel094144/Daniel/SpokenQA/train-hash2question.json', '/home/daniel094144/Daniel/SpokenQA/dev-hash2question.json']
  ext: 'mp3'
  feature_selection: 12
  downsample_factor: 4

hparas: 
  n_epoch: 20
  batch_size: 4
  optimizer: 'AdamW'
  lr: 1e-4

model: 
  hidden_size: 768
  num_attention_heads: 4
  nlayers: 3
  hidden_dropout_prob: 0.1
  intermediate_size: 1024
  hidden_act: 'gelu'
  layer_norm_eps: 1e-12
  num_labels: 2
  max_position_embeddings: 1250
  segment_type_size: 2

