split: ['train', 'dev']  # either 'train' or other 
data: 
  segment_file_dir: ['./train_audios', './dev_audios']
  passage_file_dir: ['./train_passage_mp3', './dev_passage_mp3']
  file_path: ['./train_ans_reduced.csv', './dev_ans_reduced.csv']
  hash2question_path: ['./train-hash2question.json', './dev-hash2question.json']
  ext: 'mp3'
  feature_selection: 12
  downsample_factor: 8

hparas: 
  n_epoch: 20
  batch_size: 64
  optimizer: 'AdamW'
  lr: 5e-4

model: 
  hidden_size: 768
  num_attention_heads: 4
  nlayers: 3
  hidden_dropout_prob: 0.1
  intermediate_size: 1024
  hidden_act: 'gelu'
  layer_norm_eps: 1e-12
  num_labels: 2
  max_position_embeddings: 1000
  segment_type_size: 2

